apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresqldb
spec:
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresqldb
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: pguser
        - name: POSTGRES_USER
          value: pguser
        - name: POSTGRES_PASSWORD
          value: pguser
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-storage1
      volumes:
      - name: postgresql-storage1
        persistentVolumeClaim:
          claimName: postgresql-pvc1
